export * from './getMarkType';
export * from './getNodeType';
export * from './isActive';
export * from './isMarkActive';
export * from './isNodeActive';
export * from './toggleNode';
export * from './updateGlobalAttrs';
export * from './getSchemaTypeNameByName';
export * from './toggleWrap';
export { default as checkViewPlugin } from './checkViewPlugin';
